import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Button from "../components/Button";
import Login from "../components/Login";
import Menu from "../components/Menu";

const Home: NextPage = () => {
  return (
    <div className="relative">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* <div className="clip h-screen w-full absolute top-0 left-0 -z-10">
        <div className="bg-[#ffd1d5] w-full h-full"></div>
      </div> */}

      <Menu></Menu>
      <div className="p-4 pt-24">
        <div className="flex h-[calc(100vh-6rem)]">
          {/* <div className="bg-[url('/images/formBackground.png')]"> */}
          <div className="body-font w-1/2 text-right flex flex-col justify-start">
            <p className=" text-[#FB506A] text-[6rem]">
              you can&apos;t buy
            </p>
            <p className=" text-[10rem]">love !</p>
            <Button>Adopt a pet today!</Button>
          </div>
          {/* </div> */}

          <div className="w-1/2 h-full flex flex-col justify-end">
            <img className="object-contain" src="/images/funnyDog.png" />
          </div>
        </div>

        <div className="bg-red-500 h-96 w-full">sub content</div>
      </div>

      <style jsx>{`
        .clip {
          clip-path: circle(100% at -50% -30%);
        }
      `}</style>
    </div>
  );
};

export default Home;
